### PR TITLE
don't reset expense form on load

### PR DESCRIPTION
**Pull request by asood123**
this fixes submitExpense issue

### CODE REVIEW

**Comment by xdamman** [comment]
why?

**Comment by asood123** [comment]
form was being rest after being loaded from `Link` in react-router.

**Comment by xdamman** [comment]
Why was that reset there in the first place?
When you click on "Submit a new expense", does it still reset it properly?

**Comment by asood123** [comment]
yes. not sure why it was there. this code is over 6 months old.

**Pull request merged**
