### PR TITLE
Pending collective

### PR DESCRIPTION
**Pull request by carlosascari**
All data is mocked right now
`group.settings.pending` must be true in order to see the pending collective view rendered.

### CODE REVIEW

**Comment by carlosascari** [comment]
@asood123 @xdamman @sedubois 
> Your build ran 84 tests in junit with 0 failures

False negative, please review

**Comment by asood123** [comment]
It timed out and didn't run e2e tests. I restarted it.

**Comment by carlosascari** [comment]
@asood123 Could you take another look, it looks like somethings wrong with the Expenses List test 
```
 ✖ expenses_page
   - Expenses list
     Testing if element <div[class=TransactionItem]:first-child> contains text: "Expense 2". Element could not be located. - Expected "Expense 2" but got: "null"
```

**Comment by asood123** [comment]
that's related to the expense refactor we have been working on. I'll take care of this PR after that's checked in.

**Comment by sedubois** [comment]
@carlosascari 

> > Your build ran 84 tests in junit with 0 failures

> False negative

That report at top of circleCi only shows mocha tests, not e2e tests (so it's not a false negative, CircleCi correctly showed that an e2e test failed).

**Pull request merged**
