### PR TITLE
Improve / fix some Spanish translations

### PR DESCRIPTION
**Pull request by dasilvacontin**
I understand that some of these may come from a Spanish dialect – I'm open to discuss solutions, since I understand that from people of X dialect it might not be acceptable to be treated using Y dialect.

Also, I made consistent the usage of su / tu, usted / ti. I personally find it excessive / old / boring to be treated with 'usted' in a modern context, but you might not hold the same opinion. Again, open to discuss :).

### CODE REVIEW

**Comment by piamancini** [comment]
yeah I agree with getting rid of usted. fixed that here https://github.com/OpenCollective/opencollective-website/pull/266. Not sure how to do this, if wait until it's pushed and then you propose changes over that?

**Comment by dasilvacontin** [comment]
@piamancini Not sure what you mean – that PR is already merged, commit is in master. My changes are already over that / on top of the changes you made, afaik.

**Comment by piamancini** [comment]
Ah, I right off course. Sorry was thinking that was before merging (it's been a very very long day). I did change the Usted right? let me see. The test didn't pass so we need to fix that as well

**Comment by piamancini** [comment]
changes are great, when test pases I can merge.

**Comment by dasilvacontin** [comment]
@piamancini Thanks!

Not sure why the tests are not passing, maybe it's a flaky E2E test:
```bash
> opencollective-website@0.1.112 rexec:api /home/ubuntu/opencollective-website
> bash scripts/remote_exec_api.sh "test_e2e.sh" "api:run" "website:run" "website:testE2E"

Output directory set to /tmp/circle-junit.nVCqB2M/e2e
Cleaning up node processes
Running step api:run
Started opencollective-api with PID 18286 and saving output to /tmp/circle-junit.nVCqB2M/e2e/opencollective-api.log
Waiting for opencollective-api startup during 20 seconds
/home/ubuntu/opencollective-api/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/ubuntu/opencollective-api/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/home/ubuntu/opencollective-api/node_modules/passport-github/lib/strategy.js:62:18)
    at module.exports.app (/home/ubuntu/opencollective-api/server/lib/express.js:31:16)
    at Object.<anonymous> (/home/ubuntu/opencollective-api/index.js:18:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```

**Comment by asood123** [comment]
We have an issue with circleci tests on forks. They won't pass e2e tests
because keys and credentials aren't passed.

Let me duplicate your changes and create a new branch when I'm back on my
computer.

**Comment by asood123** [comment]
duplicated here: https://github.com/OpenCollective/opencollective-website/pull/269

**Pull request closed without merging**
