### PR TITLE
Smaller CollectiveCard component

### PR DESCRIPTION
**Pull request by carlosascari**
use className `CollectiveCard--large` to revert to original (larger) size, default will be the smaller card

Preview

### CODE REVIEW

**Comment by asood123** [comment]
@carlosascari could we reduce the size of the description section as well? The symmetry (where it's equal to the image) or even a little bit smaller looks better. What do you think @erickrico?

**Comment by carlosascari** [comment]
@asood123 
I am hesitant to reduce the font size of the description further, it is now at 14px (from 16px). Anything less, I believe will hurt readability

**Comment by asood123** [comment]
@carlosascari not the font size but the overall space given to description. How many characters can it fit right now?

**Comment by carlosascari** [comment]
Currently the max number of character that fit is about 220
Here is the card reduced in height by ~20px so as to shrink the space in the description
preview

How does that look?

**Comment by asood123** [comment]
LGTM.

**Pull request merged**
