### PR TITLE
use port 4445 for selenium server; closes #229

### LINKED ISSUE #229: selenium server port 4444 conflicts with krb524 service
if you're like me, you have a service running on port `4444` already.  

and if you're like me, you are a dummy, and aren't really sure how to disable that service.  

at any rate, I hope it can be safely changed.

### PR DESCRIPTION
**Pull request by boneskull**

### CODE REVIEW

**Comment by asood123** [comment]
I want to merge this but we need to run tests on it before we can do that. Any ideas why tests didn't run? @sedubois

**Comment by sedubois** [comment]
@asood123 don't know top of my head either. Related to being a fork? @boneskull can you also rebase on master just to be sure?

**Comment by boneskull** [comment]
as per @asood123 i'm going to re-open this from the main repo

**Comment by boneskull** [comment]
@asood123 I'll need to have write access here too

**Comment by boneskull** [comment]
(was going to make a new branch here and re-create this PR from it)

**Comment by boneskull** [comment]
(unless of course you'd like me to figure out why the PR's aren't running)

**Pull request closed without merging**
