### PR TITLE
propose new tagline

### PR DESCRIPTION
**Pull request by piamancini**
I'd like to include the idea of a shared mission and make it about people not about an association.

### CODE REVIEW

**Comment by sedubois** [comment]
BTW I like Musk's view of business (or lack thereof) - "I don't know what a business is. All a company is is a bunch of people together to create a product or service. There's no such thing as a business, just pursuit of a goal — a group of people pursuing a goal."

http://www.techinsider.io/elon-musk-says-theres-no-such-thing-as-a-business-2015-9

**Comment by piamancini** [comment]
@sedubois I was also playing with the idea of 'shared purpose' instead of mission but since we use mission on our public page, it seemed more fitting

**Comment by asood123** [comment]
👍  for new definition of open collective

**Comment by sedubois** [comment]
I prefer the purpose wording as it's more applicable on an individual level ("life purpose", "inner purpose", etc) and so the collective is just a reflection of the individuals. Mission keeps things a little depersonalized, but it's getting technical, mission works too at this point IMHO

**Pull request merged**
