### PR TITLE
Pending collective

### PR DESCRIPTION
**Pull request by asood123**
Reopening this, since this has mocked data

### CODE REVIEW

**Comment by carlosascari** [comment]
@asood123 
I was hoping this would be merged, since it wont activate/show until `group.settings.pending` is true.
The reason is because I want to reuse the `ContributorList` component in this PR, for this newer issue https://github.com/OpenCollective/OpenCollective/issues/122

Should I go ahead and make a PR withe the `ContributorList` component instead?

**Comment by asood123** [comment]
Didn't want to push dummy data. I can point you to real data tmrw.

**Comment by carlosascari** [comment]
@asood123 
Could you tell me what link I should put here:
preview

**Comment by asood123** [comment]
We can link that to a FAQ when we release it. For now, feel free to remove the link.

**Comment by asood123** [comment]
What's going on with this PR?

**Comment by carlosascari** [comment]
@asood123 The last commit `Fixed fee calculations`, should calculate the right fees however, I don't know if you've reviewed the changes?

**Comment by asood123** [comment]
Ah right. Will review.

**Pull request merged**
