### PR TITLE
Allow to display also inactive/one-time sponsors in embedded list and JSON data

### PR DESCRIPTION
**Pull request by sokra**
Currently the lists doesn't show one-time sponsors, because they are not "active".

This PR fixes this and shows every sponsor regardless of activity.

This aligns the embedded sponsor list with the list on the opencollective website.

### CODE REVIEW

**Comment by asood123** [comment]
@sokra We made this change on request from several collectives, who only wanted to see the current sponsors showing upon their github page and widget. Maybe it makes more sense to include one-time donators as active users for a period?

**Comment by sokra** [comment]
If "active" is define as doing any donation a one-time sponsor can donate $1/month to be in the list. A small donation makes big difference if you know the system. Are you fine with making this a query option?

**Comment by sokra** [comment]
I changed the PR to keep the original behavior but added a query param `requireActive` which allows to override the behavior.

This should allow to opt-in to disable inactive users in the list.

**Comment by asood123** [comment]
Thanks @sokra

**Comment by asood123** [comment]
Circle CI doesn't run on forks... Let me fork this change so tests run to make sure nothing will break

**Comment by asood123** [comment]
Generated a new PR to get tests to run: https://github.com/OpenCollective/opencollective-website/pull/701

**Comment by sokra** [comment]
@asood123 This worked for a while, but seem to be broken again now.

---

https://opencollective.com/webpack/sponsor/0/avatar?requireActive=true


---

https://opencollective.com/webpack/sponsor/0/avatar?requireActive=false


---

The second one should be Capital One instead like on the opencollective website:

image

**Pull request closed without merging**
