### PR TITLE
Added mailchimp input for waiting list in homepage

### PR DESCRIPTION
**Pull request by carlosascari**
Set overall opacity of homepage bg to 70%
Minor 'css collision' fixes
Added new component homepage/`MailChimpInputSection`

### CODE REVIEW

**Comment by xdamman** [comment]
Nicely done. It's beautiful.
I've just made a small change to keep it open all the time to increase conversion rate.
Also, FYI I had to change the `componentWillMount` to `componentWillReceiveProps` otherwise `document` would not be set when the page is pre-rendered by the backend.

Great job!

**Comment by carlosascari** [comment]
@xdamman If we include another [MailChimp List Id](https://github.com/OpenCollective/opencollective-website/blob/61348b822df150bd88b88fefb4b94c93f344558a/frontend/src/components/homepage/MailChimpInputSection.js#L9), we can use it to add a second email input under the `Become a sponsor` button, since right now it is also a `mailto:` link. What do you think?

**Comment by xdamman** [comment]
That's a great idea. Here is a list id for sponsors: `4cbda7da19`
Maybe make this one "onclick" so that there is only one visible form by default

**Comment by xdamman** [comment]
I'll merge this once the tests pass so do another PR.

**Comment by xdamman** [comment]
@carlosascari there is one bug: if you hit enter instead of clicking on the button it doesn't work (it returns an error which is annoying)

**Pull request merged**
