### PR TITLE
Contributors are listed when group.data.githubUsers is an object:

### PR DESCRIPTION
**Pull request by carlosascari**
with a username as key and its value the total number of commits.
Modified UserPhoto so it listens to hover events.

For https://github.com/OpenCollective/OpenCollective/issues/122

As long as `group.data.githubUsers` is falsy it will not display. 
Contributors are sorted so core contributors are first followed by number of commits after.
Only commits are displayed, if additions and/or deletions are included they will be displayed as well.

@asood123 @boneskull  
`group.data` does not tell us whether a user is a core contributor or not. How can we determine core contributors?

### CODE REVIEW

**Comment by asood123** [comment]
What would the definition of a core contributor be? @boneskull

**Comment by xdamman** [comment]
I'd say that core contributors should have an open collective account and be MEMBERS of the collective. @carlosascari can you make it that way and make sure there is no duplicate?

**Comment by asood123** [comment]
Are you still working on this, @carlosascari or should I merge?

**Comment by carlosascari** [comment]
@asood123 
The task based on the mockup by Erick shows contributors ordered by importance where core contributors are listed first, then by total contributions. There is no `core` information in items from `group.data.githubUsers`, so contributors will never be ordered by being a core member, they will only be ordered by their total contributions.

Items in `group.data.githubUsers`, instead of being the number of contributions it could be an object with *contributions*, *deletions*, *additions* and a *core* boolean

It works, but it is not complete

**Comment by boneskull** [comment]
What's "deletions" and "additions"?

The "core" boolean seems unnecessary if we have a definition of who is a "core" contributor elsewhere in the DB.  We can then store an *email address* (in addition to the GitHub username) in order to perform the lookup.  Granted, this should all be part of an actual schema instead of a JSON blob once things settle down.

I explained to @xdamman in Slack where to add more user data...

**Comment by carlosascari** [comment]
@boneskull 
By core I was referring to the actual variable used in the code in this PR to order contributos see: https://github.com/OpenCollective/opencollective-website/pull/292/files#diff-922bbe5781cbfbe31e15ca1525fdea6fR106

Deletions and additions as well as commits are displayed on the hover card
https://github.com/OpenCollective/OpenCollective/issues/33#issuecomment-217232132

**Pull request merged**
