### PR TITLE
[ONGOING] Homepage

### PR DESCRIPTION
**Pull request by carlosascari**
@asood123
You **must** use the `homepage` branch on the api repo: 
https://github.com/OpenCollective/opencollective-api/pull/469

There are 4 points I want to cover, the last 2 are questions.

1) The login top header has not been included, it will be its own PR.
*related:* 
- https://github.com/OpenCollective/OpenCollective/issues/154
- https://github.com/OpenCollective/OpenCollective/issues/155

2) Currently, the `/homepage` api endpoint does not include:
-  *backers count*
- *sponsors count*
-  *monthly income/budget*

for each group represented by the [*CollectiveCard* component](https://github.com/OpenCollective/opencollective-website/pull/319).

*related*:
- https://github.com/OpenCollective/opencollective-website/pull/319
- https://github.com/OpenCollective/opencollective-api/pull/470

3) The new homepage design includes a button `Join The Waiting List!` button. Where will it redirected to?

4) There is also a link `Learn more about the collectives`, where will it redirect to?

### CODE REVIEW

**Comment by asood123** [comment]
#3: Re: join the waiting list. Can we point it to the current Join the Waiting List link? @piamancini 

#4: @piamancini where should that link go?

**Comment by piamancini** [comment]
@asood123 it should go to the form that was used in the static-website linked to our mailchimp

**Comment by asood123** [comment]
@carlosascari This is where it was going before. https://github.com/OpenCollective/website-static/blob/master/views/partials/mailchimp.hbs. Are you up for implementing that on this repo?

**Comment by asood123** [comment]
@carlosascari can you remove the #4 link for now?

**Comment by carlosascari** [comment]
Sure, I'll take care of it, It will need Erick to quickly design the input somewhere. I'll send a PR with the changes and notify you, @asood123. I will remove the **4)** link now

**Pull request merged**
